experiment_parameters:
  num_runs: 1
  num_episodes: 300
  timeout: 500

agent_parameters:
  network_config:
    state_dim: 8
    num_hidden_units: 256
    num_actions: 4
  optimizer_config:
    step_size: 0.001
    beta_m: 0.9
    beta_v: 0.999
    epsilon: 0.00000001
  replay_buffer_size: 50000
  minibatch_sz: 8
  num_replay_updates_per_step: 4
  gamma: 0.99
  tau: 0.001
